---
- name: Docker deployment
  hosts: client1
  gather_facts: yes
  become: yes
  tasks:
    - name: pull docker images
      shell: docker pull ascay/devopsimg

    - name: run container
      shell: docker run -it -d --name devopspipelinecalsci ascay/devopsimg
